// Generated by https://pagedraw.io/pages/1
import { Component, Input, Output, EventEmitter  } from '@angular/core';

@Component({
    selector: 'angularcomponent',
    templateUrl: './angularcomponent.component.html',
    styleUrls: ['./angularcomponent.component.css']
})
export class Angularcomponent {
    @Input() text: string;
}