// Generated by https://pagedraw.io/pages/1
import { NgModule } from '@angular/core'
import { CommonModule } from '@angular/common'
import { Angularcomponent } from './angularcomponent/angularcomponent.component';

@NgModule({
    imports: [ CommonModule ],
    declarations: [
        Angularcomponent
    ],
    exports: [
        Angularcomponent
    ]
})
export class PagedrawModule { }